% Spline Wavelet Analysis with Different Spline Orders
clear all; close all; clc;

% Generate test signal
t = 0:0.001:1;
signal = sin(2*pi*10*t) + 0.5*sin(2*pi*50*t) + 0.2*sin(2*pi*100*t);

% Analysis parameters
decomposition_level = 3;
spline_orders = 1:4;
num_orders = length(spline_orders);

% Create figure for comparison
figure('Position', [100 100 1400 800]);

% Analyze each spline order
mse_all = zeros(decomposition_level, num_orders);
for idx = 1:num_orders
    current_order = spline_orders(idx);
    [approx, details, mse] = spline_wavelet_decomp(signal, decomposition_level, current_order);
    mse_all(:, idx) = mse;
    
    % Plot approximation for this order
    subplot(2, num_orders, idx);
    t_approx = linspace(0, 1, length(approx{decomposition_level}));
    plot(t_approx, approx{decomposition_level}, 'LineWidth', 1.5);
    title(sprintf('Order %d Spline Approximation', current_order));
    xlabel('Time');
    ylabel('Amplitude');
    grid on;
    
    % Plot details for final level
    subplot(2, num_orders, idx + num_orders);
    t_detail = linspace(0, 1, length(details{decomposition_level}));
    plot(t_detail, details{decomposition_level}, 'LineWidth', 1.5);
    title(sprintf('Order %d Detail Coefficients', current_order));
    xlabel('Time');
    ylabel('Amplitude');
    grid on;
end

% Create information text using vertcat
info_text = {...
    'SPLINE CHARACTERISTICS', ...
    '', ...
    'Order 1 (Linear):', ...
    '• Simplest form', ...
    '• Sharp transitions', ...
    '• Good for discontinuous signals', ...
    '', ...
    'Order 2 (Quadratic):', ...
    '• Smoother approximation', ...
    '• Better frequency localization', ...
    '• Good for smooth signals', ...
    '', ...
    'Order 3 (Cubic):', ...
    '• Excellent smoothness', ...
    '• Good time-frequency localization', ...
    '• Popular choice for many applications', ...
    '', ...
    'Order 4 (Quartic):', ...
    '• Highest smoothness', ...
    '• Best frequency localization', ...
    '• May over-smooth sharp features', ...
    '', ...
    'MSE ANALYSIS:', ...
    sprintf('Order 1: %.6f', mean(mse_all(:,1))), ...
    sprintf('Order 2: %.6f', mean(mse_all(:,2))), ...
    sprintf('Order 3: %.6f', mean(mse_all(:,3))), ...
    sprintf('Order 4: %.6f', mean(mse_all(:,4))), ...
    '', ...
    'RECOMMENDATIONS:', ...
    'Order 1: For signals with jumps/discontinuities', ...
    'Order 2: For signals with sharp transitions', ...
    'Order 3: For general-purpose analysis', ...
    'Order 4: For very smooth signals'};

% Add information text box
annotation('textbox', [0.02 0.1 0.25 0.8], ...
    'String', info_text, ...
    'EdgeColor', 'k', ...
    'BackgroundColor', 'w', ...
    'FitBoxToText', 'on', ...
    'FontSize', 9);

sgtitle('Comparison of Different Spline Orders in Wavelet Analysis', ...
    'FontSize', 14, 'FontWeight', 'bold');